blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_index'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail_sending.urls', namespace='mail_sending')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('client/', include('client.urls', namespace='client')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail_sending/urls.py
from django.urls import path
from mail_sending.views import index
from mail_sending.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView
from mail_sending.views import MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView
from mail_sending.views import LogListView, LogDetailView

from .apps import MailSendingConfig

app_name = MailSendingConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('mail_sending/', MailingListView.as_view(), name='mail_sending_index'),
    path('mail_sending/create/', MailingCreateView.as_view(), name='mail_sending_create'),
    path('mail_sending_detail/<int:pk>/', MailingDetailView.as_view(), name='mail_sending_detail'),
    path('mail_sending/update/<int:pk>/', MailingUpdateView.as_view(), name='mail_sending_update'),
    path('mail_sending/delete/<int:pk>/', MailingDeleteView.as_view(), name='mail_sending_delete'),
    path('message/', MessageListView.as_view(), name='message_index'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message_detail/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('log/', LogListView.as_view(), name='log_index'),
    path('log_detail/<int:pk>/', LogDetailView.as_view(), name='log_detail'),

]

mail_sending/models.py
from django.utils import timezone
from django.db import models
from client.models import Client
from users.models import User

# Constants

NULLABLE = {'blank': True, 'null': True}


class PeriodMail(models.TextChoices):
    DAYLE = "DY", 'Раз в день'
    WEEKLY = "WK", 'Раз в неделю'
    MONTLY = "MY", 'Раз в месяц'


class StatusMail(models.TextChoices):
    CREATED = "CR", 'Создана'
    RUNNING = "RU", 'Запущена'
    COMPLETED = "CO", 'Завершена'


class StatusLog(models.TextChoices):
    SUCCESS = "SU", 'Успешно'
    FAILURE = "FA", 'Ошибка'



class MailDistribution(models.Model):

    period_in_time = models.CharField(max_length=10, choices=PeriodMail.choices,  verbose_name='Периодичность рассылки')
    status = models.CharField(max_length=10, choices=StatusMail.choices, verbose_name='Статус рассылки')
    status_log = models.CharField(max_length=10, choices=StatusLog.choices, verbose_name='Статус попытки')

    def str(self):
        return self.period_in_time

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ('period_in_time',)
# Message


class Message(models.Model):
    """Сообщение для рассылки"""
    title = models.CharField(max_length=100, verbose_name='Тема письма')
    text = models.TextField(verbose_name='Тело письма')
    #owner = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец"')

    def str(self):
        return self.title

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'
        ordering = ('title',)




class Mailing(models.Model):
    '''Рассылка'''
    title = models.CharField(max_length=100, verbose_name='Название')
    client = models.ManyToManyField(Client, verbose_name='Клиенты для рассылки')
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Сообщение')
    time_mail = models.DateTimeField(default=timezone.now, verbose_name='Время рассылки')
    period_mail = models.CharField(max_length=50, verbose_name='Период рассылки', choices=PeriodMail.choices)
    status_mail = models.CharField(max_length=50, default='created', verbose_name='Статус рассылки',
                                   choices= StatusMail.choices)
    #owner = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')

    def str(self):
        return self.title

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ('time_mail',)


class Log(models.Model):
    '''Логи рассылки'''
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, **NULLABLE, verbose_name='Рассылка')
    datetime_attempt = models.DateTimeField(default=timezone.now, verbose_name='Дата последней попытки')
    status_attempt = models.CharField(choices=StatusLog.choices, max_length=50, verbose_name='Статус попытки')
    answer_server = models.TextField(**NULLABLE, verbose_name='Ответ сервера')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, **NULLABLE, verbose_name='Сообщение')

    def str(self):
        return f"Время рассылки: {self.datetime_attempt}"

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'
        ordering = ('datetime_attempt',)

mail_sending/forms.py
from django import forms
from mail_sending.models import Mailing, Message, Log


class StyleFormMixin:
    '''Стилизация'''

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    '''Формы рассылки для CREATE и UPDATE'''

    class Meta:
        model = Mailing
        fields = ('title', 'client', 'time_mail', 'period_mail', 'status_mail',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    '''Сообщение'''

    class Meta:
        model = Message
        fields = '__all__'


class LogForm(StyleFormMixin, forms.ModelForm):
    '''Логи'''

    class Meta:
        model = Log
        fields = '__all__'

mail_sending/views.py
from django.shortcuts import render
from random import sample
from mail_sending.models import Message, Mailing, Log
from client.models import Client
from blog.models import Blog
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from mail_sending.forms import MailingForm, MessageForm

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

from mail_sending.mailing_services import send_mailing


'''ГЛАВНАЯ'''
# --------------------------------------------------------------------------------------------------------------------------------

def index(request):
    '''Главная страница'''
    total_mailings = Mailing.objects.count()  # всего рассылок
    # active_mailings = Mailing.objects.filter(status='running').count()  # всего активных рассылок
    unique_clients = Client.objects.distinct().count()  # всего уникальных клиентов
    all_posts = Blog.objects.filter(is_published=True)  # все блог-посты

    if len(all_posts) >= 3:
        random_posts = sample(list(all_posts), 3)  # 3 случайных блог-поста
    elif len(all_posts) == 0:
        random_posts = None
    else:
        random_posts = sample(list(all_posts), 1)

    context = {'total_mailings': total_mailings,
               # 'active_mailings': active_mailings,
               'unique_clients': unique_clients,
               'posts': random_posts}

    return render(request, 'mail_sending/index.html', context)



'''РАССЫЛКИ - Mailing'''
# --------------------------------------------------------------------------------------------------------------------------------

class MailingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    '''CREATE - создается карточка рассылки'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mail_sending:mail_sending_index')
    permission_required = 'mail_sending.add_mailing'

    #def form_valid(self, form):
        #if form.is_valid():
            #new_mat = form.save()
            #new_mat.save()

        #return super().form_valid(form)

    def form_valid(self, form):
        self.object = form.save()
        self.object.status_mail = 'created'
        self.object.save()
        if self.object.status_mail in ('running', 'created'):
            send_mailing(self.object)
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)



class MailingListView(LoginRequiredMixin, ListView):
    '''READ - чтение списка рассылок'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''

    model = Mailing
    template_name = 'mail_sending/mail_sending_index.html'


class MailingDetailView(LoginRequiredMixin, DetailView):
    '''READ - чтение одной рассылки'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''

    model = Mailing
    success_url = reverse_lazy('mail_sending:mail_sending_detail')


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''UPDATE - обновление записи рассылки'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mail_sending:mail_sending_index')
    permission_required = 'mail_sending.change_mailing'

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mail_sending:mail_sending_detail', args=[self.kwargs.get('pk')])


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    '''DELETE - удаление записи рассылки'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Mailing
    success_url = reverse_lazy('mail_sending:mail_sending_index')
    permission_required = 'mail_sending.delete_mailing'



'''СООБЩЕНИЕ - Message'''
# --------------------------------------------------------------------------------------------------------------------------------

class MessageCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    '''CREATE - создается сообщение'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mail_sending:message_index')
    permission_required = 'mail_sending.add_message'

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.save()

        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    '''READ - чтение списка сообщений'''

    model = Message
    template_name = 'mail_sending/message_index.html'


class MessageDetailView(LoginRequiredMixin, DetailView):
    '''READ - чтение одного сообщения'''

    model = Message
    success_url = reverse_lazy('mail_sending:message_detail')


class MessageUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''UPDATE - обновление сообщения'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mail_sending:message_index')
    permission_required = 'mail_sending.change_message'

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mail_sending:message_detail', args=[self.kwargs.get('pk')])


class MessageDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    '''DELETE - удаление сообщения'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Message
    success_url = reverse_lazy('mail_sending:message_index')
    permission_required = 'mail_sending.delete_message'


'''ЛОГИ - log'''
# --------------------------------------------------------------------------------------------------------------------------------

class LogListView(LoginRequiredMixin, ListView):
    '''READ - чтение списка логов'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''

    model = Log
    template_name = 'mail_sending/log_index.html'


class LogDetailView(LoginRequiredMixin, DetailView):
    '''READ - чтение одного лога'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''

    model = Log
    success_url = reverse_lazy('mail_sending:log_detail')

mail_sending/templates/mail_sending/index.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<div class="row justify-content-center">


    <div class="container mb-5">
        <div class="row">
            <div class="col-sm-4">
                <h5 class="card-title text-muted text-center font-weight-bold">Всего рассылок</h5>
                <p class="text-center">{{ total_mailings }}</p>
            </div>
            <div class="col-sm-4">
                <h5 class="card-title text-muted text-center font-weight-bold">Активные рассылки</h5>
                <p class="text-center"> 0 <!-- {{ active_mailings }} --></p>
            </div>
            <div class="col-sm-4">
                <h5 class="card-title text-muted text-center font-weight-bold">Уникальные клиенты</h5>
                <p class="text-center">{{ unique_clients }}</p>
            </div>
        </div>
    </div>

    <div class="album py-5 bg-light">
    <div class="container">
        <h5 class="card-title text-muted text-center font-weight-bold">Блог посты</h5>
        <br>
        <br>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center">
        {% for object in posts %}

            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark">
                        <h4 class="my-0 fw-normal text-center">{{ object.title|title }}</h4>
                    </div>

                    <div class="card-body">

                        <img src="/media/{{ object.image }}" height="100%" width="100%"/>
                        <p class="card-text">Описание: {{ object.content }}</p>
                        <p class="card-text">Дата создания: {{ object.data_create }}</p>
                        <p class="card-text">Дата редактирования: {{ object.is_published}}</p>
                        <p class="card-text">Количество просмотров: {{ object.views_count}}</p>

                        <hr>


                        <a href="{% url 'blog:blog_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Блог</a>

                    </div>
                </div>

            </div>


               {% endfor %}

    </div>



    </div>
    </div>

</div>


{% endblock %}

mail_sending/templates/mail_sending/log_detail.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark">
                        <h4 class="my-0 fw-normal text-center">{{ object.datetime_attempt|title }}</h4>
                    </div>

                    <div class="card-body">

                        <p class="card-text">Сообщение: {{ object.message }}</p>
                        <p class="card-text">Дата: {{ object.datetime_attempt }}</p>
                        <p class="card-text">Статус: {{ object.status_attempt }}</p>
                        <p class="card-text">Ответ: {{ object.answer_server }}</p>


                        <hr>


                        <a href="{% url 'mail_sending:log_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>


</div>

{% endblock %}

mail_sending/templates/mail_sending/log_index.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Логи</h1><br>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center">
                {% for object in object_list %}


                <div class="col-md-5">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark text-center">
                        <h4 class="my-0 fw-normal">{{ object.datetime_attempt|title }}</h4>
                    </div>

                    <div class="card-body">
                        <p>{{ object.message }}</p>

                        <a href="{% url 'mail_sending:log_detail' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg">Подробнее</a>
                        <hr>



                    </div>

                </div>

            </div>


                {% endfor %}
            </div>
        </div>
    </div>


{% endblock %}

mail_sending/templates/mail_sending/mail_sending_confirm_delete.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<form method="post">

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        Удаление поста
                    </div>

                    <div class="card-body">

                            {% csrf_token %}
                            <p>Вы действительно хотите удалить запись - {{ object.title }} ?</p>
                            <button type="submit" class="btn btn-outline-danger">
                                Удалить
                            </button>
                            <a class="btn btn-outline-warning" href="{% url 'mail_sending:mail_sending_index' %}">Отмена</a>

                        <a href="{% url 'mail_sending:mail_sending_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>
            </div>

</form>


{% endblock %}

mail_sending/templates/mail_sending/mail_sending_detail.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark">
                        <h4 class="my-0 fw-normal text-center">{{ object.title|title }}</h4>
                    </div>

                    <div class="card-body">

                        <p class="card-text">Время рассылки: {{ object.time_mail }}</p>
                        <p class="card-text">Период рассылки: {{ object.period_mail }} </p>
                        <p class="card-text">Статус рассылки: {{ object.status_mail }}</p>


                        <hr>

                        <div class="btn-group">
                            {% if perms.mail_sending.change_mailing %}
                            <a href="{% url 'mail_sending:mail_sending_update' object.pk %}" class="btn btn-outline-success">Edit</a>
                            {% endif %}
                            {% if perms.mail_sending.delete_mailing %}
                            <a href="{% url 'mail_sending:mail_sending_delete' object.pk %}" class="btn btn-outline-danger">Delete</a>
                            {% endif %}
                        </div>

                        <a href="{% url 'mail_sending:mail_sending_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>


</div>

{% endblock %}

mail_sending/templates/mail_sending/mail_sending_form.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        {% if object %}
                            Редактировать
                        {% else %}
                            Добавить
                        {% endif %}

                    </div>

                    <div class="card-body">

                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-outline-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>

                        <a href="{% url 'mail_sending:mail_sending_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>
            </div>

</form>



{% endblock %}

mail_sending/templates/mail_sending/mail_sending_index.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Рассылки</h1><br>
                {% if perms.mail_sending.add_mailing %}
                <p>
                    <a class="btn btn-outline-dark btn-lg" href="{% url 'mail_sending:mail_sending_create' %}">Создать рассылку</a>
                </p>
                {% endif %}
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center">
                {% for object in object_list %}


                <div class="col-md-5">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark text-center">
                        <h4 class="my-0 fw-normal">{{ object.title|title }}</h4>
                    </div>

                    <div class="card-body">

                        <p>Статус рассылки: {{ object.status_mail }}</p>

                        <a href="{% url 'mail_sending:mail_sending_detail' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg">Подробнее</a>
                        <hr>

                        <div class="btn-group">
                            {% if perms.mail_sending.change_mailing %}
                            <a href="{% url 'mail_sending:mail_sending_update' object.pk %}" class="btn btn-outline-success">Edit</a>
                            {% endif %}
                            {% if perms.mail_sending.delete_mailing %}
                            <a href="{% url 'mail_sending:mail_sending_delete' object.pk %}" class="btn btn-outline-danger">Delete</a>
                            {% endif %}
                        </div>



                    </div>

                </div>

            </div>


                {% endfor %}
            </div>
        </div>
    </div>






{% endblock %}

mail_sending/templates/mail_sending/message_confirm_delete.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<form method="post">

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        Удаление поста
                    </div>

                    <div class="card-body">

                            {% csrf_token %}
                            <p>Вы действительно хотите удалить запись - {{ object.title }} ?</p>
                            <button type="submit" class="btn btn-outline-danger">
                                Удалить
                            </button>
                            <a class="btn btn-outline-warning" href="{% url 'mail_sending:message_index' %}">Отмена</a>

                        <a href="{% url 'mail_sending:message_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>
            </div>

</form>


{% endblock %}

mail_sending/templates/mail_sending/message_detail.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark">
                        <h4 class="my-0 fw-normal text-center">{{ object.title|title }}</h4>
                    </div>

                    <div class="card-body">

                        <p class="card-text">Название: {{ object.title }}</p>
                        <p class="card-text">Содержание: {{ object.text }}</p>


                        <hr>

                        <div class="btn-group">
                            {% if perms.mail_sending.change_message %}
                            <a href="{% url 'mail_sending:message_update' object.pk %}" class="btn btn-outline-success">Edit</a>
                            {% endif %}
                            {% if perms.mail_sending.delete_message %}
                            <a href="{% url 'mail_sending:message_delete' object.pk %}" class="btn btn-outline-danger">Delete</a>
                            {% endif %}
                        </div>

                        <a href="{% url 'mail_sending:message_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>


</div>

{% endblock %}

mail_sending/templates/mail_sending/message_form.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        {% if object %}
                            Редактировать
                        {% else %}
                            Добавить
                        {% endif %}

                    </div>

                    <div class="card-body">

                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-outline-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>

                        <a href="{% url 'mail_sending:message_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>
            </div>

</form>



{% endblock %}

mail_sending/templates/mail_sending/message_index.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Сообщения</h1><br>
                {% if perms.mail_sending.add_message %}
                <p>
                    <a class="btn btn-outline-dark btn-lg" href="{% url 'mail_sending:message_create' %}">Создать сообщение</a>
                </p>
                {% endif %}
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center">
                {% for object in object_list %}


                <div class="col-md-5">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark text-center">
                        <h4 class="my-0 fw-normal">{{ object.title|title }}</h4>
                    </div>

                    <div class="card-body">
                        <p>Название: {{ object.title }}</p>
                        <p>Содержание: {{ object.text|truncatechars:100 }}</p>

                        <a href="{% url 'mail_sending:message_detail' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg">Подробнее</a>
                        <hr>

                        <div class="btn-group">
                            {% if perms.mail_sending.change_message %}
                            <a href="{% url 'mail_sending:message_update' object.pk %}" class="btn btn-outline-success">Edit</a>
                            {% endif %}
                            {% if perms.mail_sending.delete_message %}
                            <a href="{% url 'mail_sending:message_delete' object.pk %}" class="btn btn-outline-danger">Delete</a>
                            {% endif %}
                        </div>



                    </div>

                </div>

            </div>


                {% endfor %}
            </div>
        </div>
    </div>


{% endblock %}