blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_index'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),

]

client/urls.py
from django.urls import path
from client.apps import ClientConfig

from client.views import ClientListView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView

app_name = ClientConfig.name

urlpatterns = [
    path('client/', ClientListView.as_view(), name='client_index'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client_detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail_sending.urls', namespace='mail_sending')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('client/', include('client.urls', namespace='client')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models
from users.models import User

# Client
NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    '''Клиент сервиса'''
    email = models.EmailField(unique=True, verbose_name='email')
    name = models.CharField(**NULLABLE, max_length=150, verbose_name='ФИО')
    comment = models.TextField(**NULLABLE, verbose_name='Комментарий')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')

    def __str__(self):
        return f'{self.email} {self.name}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

client/forms.py
from django import forms
from client.models import Client


class StyleFormMixin:
    '''Стилизация'''

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    '''Формы для CREATE и UPDATE'''

    class Meta:
        model = Client
        fields = ('email', 'name', 'comment', 'owner',)

client/views.py
from django.shortcuts import render
from client.models import Client
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from client.forms import ClientForm

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required


class ClientCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    '''CREATE - создается карточка клиента'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('client:client_index')
    permission_required = 'client.add_client'

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.save()

        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    '''READ - чтение списка клиентов'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''

    model = Client
    template_name = 'client/client_index.html'


class ClientDetailView(LoginRequiredMixin, DetailView):
    '''READ - чтение одной записи клиента'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''

    model = Client
    success_url = reverse_lazy('client:client_detail')


class ClientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''UPDATE - обновление записи клиента'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('client:client_index')
    permission_required = 'client.change_client'

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('client:client_detail', args=[self.kwargs.get('pk')])


class ClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    '''DELETE - удаление записи клиента'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Client
    success_url = reverse_lazy('client:client_index')
    permission_required = 'client.delete_client'

client/templates/client/client_confirm_delete.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<form method="post">

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        Удаление поста
                    </div>

                    <div class="card-body">

                            {% csrf_token %}
                            <p>Вы действительно хотите удалить запись - {{ object.name }} ?</p>
                            <button type="submit" class="btn btn-outline-danger">
                                Удалить
                            </button>
                            <a class="btn btn-outline-warning" href="{% url 'client:client_index' %}">Отмена</a>

                        <a href="{% url 'client:client_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>
            </div>

</form>


{% endblock %}

client/templates/client/client_detail.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark">
                        <h4 class="my-0 fw-normal text-center">{{ object.name|title }}</h4>
                    </div>

                    <div class="card-body">

                        <p class="card-text">ФИО: {{ object.name }}</p>
                        <p class="card-text">Почта: {{ object.email }}</p>
                        <p class="card-text">Комментарий: {{ object.comment }}</p>


                        <hr>

                        <div class="btn-group">
                            {% if perms.client.change_client %}
                            <a href="{% url 'client:client_update' object.pk %}" class="btn btn-outline-success">Edit</a>
                            {% endif %}
                            {% if perms.client.delete_client %}
                            <a href="{% url 'client:client_delete' object.pk %}" class="btn btn-outline-danger">Delete</a>
                            {% endif %}
                        </div>

                        <a href="{% url 'client:client_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>


</div>

{% endblock %}

client/templates/client/client_form.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        {% if object %}
                            Редактировать
                        {% else %}
                            Добавить
                        {% endif %}

                    </div>

                    <div class="card-body">

                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-outline-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>

                        <a href="{% url 'client:client_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>
            </div>

</form>



{% endblock %}

client/templates/client/client_index.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Клиенты</h1><br>
                {% if perms.client.add_client %}
                <p>
                    <a class="btn btn-outline-dark btn-lg" href="{% url 'client:client_create' %}">Создать клиента</a>
                </p>
                {% endif %}
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center">
                {% for object in object_list %}


                <div class="col-md-5">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark text-center">
                        <h4 class="my-0 fw-normal">{{ object.name|title }}</h4>
                    </div>

                    <div class="card-body">
                        <p>ФИО: {{ object.name }}</p>
                        <p>Почта: {{ object.email }}</p>
                        <p>Комментарий: {{ object.comment|truncatechars:100 }}</p>

                        <a href="{% url 'client:client_detail' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg">Подробнее</a>
                        <hr>

                        <div class="btn-group">
                            {% if perms.client.change_client %}
                            <a href="{% url 'client:client_update' object.pk %}" class="btn btn-outline-success">Edit</a>
                            {% endif %}
                            {% if perms.client.delete_client %}
                            <a href="{% url 'client:client_delete' object.pk %}" class="btn btn-outline-danger">Delete</a>
                            {% endif %}
                        </div>



                    </div>

                </div>

            </div>


                {% endfor %}
            </div>
        </div>
    </div>






{% endblock %}