blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_index'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail_sending.urls', namespace='mail_sending')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('client/', include('client.urls', namespace='client')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.utils import timezone
from django.db import models

# Constants
NULLABLE = {'blank': True, 'null': True}


# Blog.
class Blog(models.Model):
    '''Блог сервиса'''
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(**NULLABLE, upload_to='blog/', verbose_name='Изображение')
    data_create = models.DateField(**NULLABLE, default=timezone.now, verbose_name='Дата публикации')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ('title',)

blog/forms.py
from django import forms
from blog.models import Blog


class StyleFormMixin:
    '''Стилизация'''

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, forms.ModelForm):
    '''Формы для CREATE и UPDATE'''

    class Meta:
        model = Blog
        fields = ('title', 'content', 'image', 'data_create', 'is_published', 'views_count',)

blog/views.py
from django.shortcuts import render
from blog.models import Blog
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from blog.forms import BlogForm

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    '''CREATE - создается запись блога'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_index')
    permission_required = 'blog.add_blog'

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.save()

        return super().form_valid(form)


class BlogListView(ListView):
    '''READ - чтение списка записей блога'''

    model = Blog
    template_name = 'blog/blog_index.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    '''READ - чтение одной записи блога'''

    model = Blog
    success_url = reverse_lazy('blog:blog_detail')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''UPDATE - обновление записи блога'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_index')
    permission_required = 'blog.change_blog'

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    '''DELETE - удаление записи блога'''
    '''LoginRequiredMixin - скрывает контент от неавторизованных пользователей'''
    '''PermissionRequiredMixin - доступ к изменению контента, permission_required = приложение.команда_модель'''

    model = Blog
    success_url = reverse_lazy('blog:blog_index')
    permission_required = 'blog.delete_blog'

blog/templates/blog/blog_confirm_delete.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<form method="post">

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        Удаление поста
                    </div>

                    <div class="card-body">

                            {% csrf_token %}
                            <p>Вы действительно хотите удалить запись - {{ object.title }} ?</p>
                            <button type="submit" class="btn btn-outline-danger">
                                Удалить
                            </button>
                            <a class="btn btn-outline-warning" href="{% url 'blog:blog_index' %}">Отмена</a>

                        <a href="{% url 'blog:blog_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>
            </div>

</form>


{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark">
                        <h4 class="my-0 fw-normal text-center">{{ object.title|title }}</h4>
                    </div>

                    <div class="card-body">

                        <img src="/media/{{ object.image }}" height="100%" width="100%"/>
                        <p class="card-text">Описание: {{ object.content }}</p>
                        <p class="card-text">Дата создания: {{ object.data_create }}</p>
                        <p class="card-text">Дата редактирования: {{ object.is_published}}</p>
                        <p class="card-text">Количество просмотров: {{ object.views_count}}</p>


                        <hr>

                        <div class="btn-group">
                            {% if perms.blog.change_blog %}
                            <a href="{% url 'blog:blog_update' object.pk %}" class="btn btn-outline-success">Edit</a>
                            {% endif %}
                            {% if perms.blog.delete_blog %}
                            <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-outline-danger">Delete</a>
                            {% endif %}
                        </div>

                        <a href="{% url 'blog:blog_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>


</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">

    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        {% if object %}
                            Редактировать
                        {% else %}
                            Добавить
                        {% endif %}

                    </div>

                    <div class="card-body">

                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-outline-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>

                        <a href="{% url 'blog:blog_index' %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg float-end">Назад</a>

                    </div>
                </div>
            </div>

</form>



{% endblock %}

blog/templates/blog/blog_index.html
{% extends 'mail_sending/base.html' %}

{% block content %}

<section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Блог</h1><br>
                {% if perms.blog.add_blog %}
                <p>
                    <a class="btn btn-outline-dark btn-lg" href="{% url 'blog:blog_create' %}">Создать пост</a>
                </p>
                {% endif %}
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center">
                {% for object in object_list %}


                <div class="col-md-5">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">

                    <div class="card-header py-3 text-bg-secondary border-dark text-center">
                        <h4 class="my-0 fw-normal">{{ object.title|title }}</h4>
                    </div>

                    <div class="card-body">
                        <img src="/media/{{ object.image }}" height="100%" width="100%"/>
                        <p>{{ object.content|truncatechars:100 }}</p>

                        <ul class="list-unstyled mt-3 mb-4">
                            <li>- Создан: {{ object.data_create }}</li>
                            <li>- Просмотров: {{ object.views_count }}</li>
                            </ul>
                        <a href="{% url 'blog:blog_detail' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary btn-lg">Подробнее</a>
                        <hr>

                        <div class="btn-group">
                            {% if perms.blog.change_blog %}
                            <a href="{% url 'blog:blog_update' object.pk %}" class="btn btn-outline-success">Edit</a>
                            {% endif %}
                            {% if perms.blog.delete_blog %}
                            <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-outline-danger">Delete</a>
                            {% endif %}
                        </div>



                    </div>

                </div>

            </div>


                {% endfor %}
            </div>
        </div>
    </div>






{% endblock %}