blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_index'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail_sending.urls', namespace='mail_sending')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('client/', include('client.urls', namespace='client')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView, ConfirmPage, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm_email/<int:pk>/', ConfirmPage.as_view(), name='confirm_email'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Users

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    first_name = models.CharField(max_length=150, verbose_name='имя', **NULLABLE)
    last_name = models.CharField(max_length=150, verbose_name='фамилия', **NULLABLE)
    surname = models.CharField(max_length=150, verbose_name='отчество', **NULLABLE)
    phone = models.CharField(max_length=40, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=100, verbose_name='страна', **NULLABLE)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    is_verified = models.BooleanField(default=False, verbose_name='Подтверждение почты', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import User
from django import forms


class StyleFormMixin:
    '''Стилизация'''

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    '''Регистрация пользователя'''

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    '''Профиль пользователя'''

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'surname', 'email', 'password', 'avatar', 'phone', 'country', 'comment', 'is_verified')

    def __init__(self, *args, **kwargs):
        '''Скрыть пароль в профиле'''
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.views.generic import CreateView, TemplateView, UpdateView
from django.urls import reverse_lazy, reverse
from users.models import User
from users.forms import UserRegisterForm, UserProfileForm
from django.shortcuts import redirect
import random
from config import settings

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.core.mail import send_mail
from users.email_services import sendmail


# Аутентификация
# ----------------------------------------------------------------
class LoginView(BaseLoginView):
    '''Контроллер входа в профиль пользователя'''
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    '''Контроллер выхода из профиля пользователя'''
    pass


class RegisterView(CreateView):
    '''Контроллер регистрации пользователя'''
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        '''Отправка письма-подтверждения на email'''

        if form.is_valid:
            new_user = form.save()
            sendmail(
                f'Для подтверждения почты пройдите по ссылке http://127.0.0.1:8000/confirm_email/{new_user.pk}/',
                (new_user.email,),
            )
        return super().form_valid(form)


class ProfileView(UpdateView):
    '''Профиль пользователя'''
    model = User
    form_class = UserProfileForm
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


# Верификация email-а
# ----------------------------------------------------------------

class ConfirmPage(TemplateView):
    '''Подтверждение почты'''
    template_name = 'users/confirm_email.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        pk = context_data['pk']
        if User.objects.filter(pk=pk).exists():
            user = User.objects.get(pk=pk)
            user.is_active = True
            user.is_staff = True
            user.save()
        return context_data


@login_required
def generate_new_password(request):
    '''Изменение пароля'''
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('mail_sending:mail_sending_index'))

users/templates/users/confirm_email.html
{% extends 'mail_sending/base.html' %}

{% block content %}



    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        <h2 class="fw-light">Подтверждение почты</h2>
                    </div>

                    <div class="card-body">

                      <span class="badge badge-success">Ваша почта подтверждена!</span>

                    </div>
                </div>
    </div>





{% endblock %}

users/templates/users/login.html
{% extends 'mail_sending/base.html' %}

{% block content %}



    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        <h2 class="fw-light">Вход</h2>
                    </div>

                    <div class="card-body">
                      <form method="post">

                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-outline-success">Войти</button>
                      </form>

                    </div>
                </div>
    </div>





{% endblock %}

users/templates/users/register.html
{% extends 'mail_sending/base.html' %}

{% block content %}



    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        <h2 class="fw-light">Регистрация</h2>
                    </div>

                    <div class="card-body">
                      <form method="post">

                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-outline-success">Регистрация</button>
                      </form>

                    </div>
                </div>
    </div>





{% endblock %}

users/templates/users/user_form.html
{% extends 'mail_sending/base.html' %}

{% block content %}



    <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm border-dark">
                    <div class="card-header py-3 text-bg-secondary border-dark">
                        <h2 class="fw-light">Профиль пользователя</h2>
                    </div>

                    <div class="card-body">
                      <form method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-outline-success">Сохранить</button>
                      </form>

                    </div>

                    <div class="card-footer py-3 text-bg-white border-dark">
                        <a href="{% url 'users:generate_new_password' %}" class="btn btn-outline-danger">Поменять пароль</a>
                    </div>

                </div>
    </div>





{% endblock %}